//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public string id { get; set; }
        public string name { get; set; }
        public string yearOfDiagnosis { get; set; }
        public string Contributorid { get; set; }
    
        public virtual Contributor Contributor { get; set; }
    }
}
