//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeechAccessibilityPersonalInformationEntities : DbContext
    {
        public SpeechAccessibilityPersonalInformationEntities()
            : base("name=SpeechAccessibilityPersonalInformationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contributor> Contributors { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
    }
}
